bindAddress: '::'
bindPort: 8080
httpGateway: {}
metadata:
  name: gateway-proxy
  namespace: gloo-system
  resourceVersion: "27"
namespacedStatuses:
  statuses:
    gloo-system:
      reportedBy: gloo
      state: Accepted
      subresourceStatuses:
        '*v1.Proxy.gateway-proxy_gloo-system':
          reportedBy: gloo
          state: Accepted
proxyNames:
- gateway-proxy
useProxyProto: false
