version: "3.7"

services:

  backend:
    build:
      context: backend

  envoy:
    command: /usr/local/bin/envoy -c /etc/envoy.yaml --service-cluster proxy --bootstrap-version 2
    image: envoyproxy/envoy-alpine:v1.17.0
    volumes:
      - ./envoy/envoy.yaml:/etc/envoy.yaml:ro
    ports:
      - "8080:8080"

  extauth:
    build:
      context: extauth

  redis:
    image: redis:6.2.1-alpine3.13

  ratelimit:
    command: /bin/ratelimit
    image: envoyproxy/ratelimit:master
    depends_on:
      - redis
    ports:
      - 8081:8080
    volumes:
      - ./ratelimit/config.yaml:/data/ratelimit/config/config.yaml:ro
    environment:
      - LOG_LEVEL=debug
      - REDIS_SOCKET_TYPE=tcp
      - REDIS_URL=redis:6379
      - RUNTIME_ROOT=/data
      - RUNTIME_SUBDIRECTORY=ratelimit
      - USE_STATSD=false
