version: "3.7"

services:

  backend:
    build:
      context: backend

  gateway:
    image: "${GLOO_REPO:-quay.io/solo-io}/gateway:${GLOO_VERSION:-1.5.12}"
    working_dir: /
    command:
    - "--dir=/data/"
    volumes:
    - ./gloo:/data/
    restart: always

  gateway-proxy:
    image: ${GLOO_REPO:-quay.io/solo-io}/gloo-envoy-wrapper:${GLOO_VERSION:-1.5.12}
    entrypoint: ["envoy"]
    command: [
      "-c", "/config/envoy.yaml",
      "--disable-hot-restart",
    ]
    volumes:
    - ./gloo/envoy.yaml:/config/envoy.yaml:ro
    ports:
    - "8080:8080"
    - "8443:8443"
    - "19000:19000"
    restart: always

  gloo:
    image: "${GLOO_REPO:-quay.io/solo-io}/gloo:${GLOO_VERSION:-1.5.12}"
    working_dir: /
    command:
    - "--dir=/data/"
    volumes:
    - ./gloo:/data/
    ports:
    - "9977:9977"
    restart: always

  extauth:
    build:
      context: extauth
