gloo:
  xdsBindAddr: 0.0.0.0:9977
metadata:
  name: default
  namespace: gloo-system
devMode: true
discoveryNamespace: gloo-system
directoryArtifactSource:
  directory: /data/artifact
directoryConfigSource:
  directory: /data/config
directorySecretSource:
  directory: /data/secret
refreshRate: 60s
watchNamespaces:
- gloo-system
extauth:
  extauthzServerRef:
    name: extauth
    namespace: gloo-system
  requestTimeout: 0.5s
ratelimitServer:
  ratelimitServerRef:
    name: ratelimit
    namespace: gloo-system
ratelimit:
  descriptors:
    - key: generic_key
      value: slowpath
      rate_limit:
        requests_per_unit: 2
        unit: MINUTE
