metadata:
  name: default
  namespace: gloo-system
  resourceVersion: "25"
namespacedStatuses:
  statuses:
    gloo-system:
      reportedBy: gloo
      state: Accepted
      subresourceStatuses:
        '*v1.Proxy.gateway-proxy_gloo-system':
          reportedBy: gloo
          state: Accepted
virtualHost:
  domains:
  - '*'
  routes:
  - matchers:
    - prefix: /
    options:
      ratelimit:
        rateLimits:
        - actions:
          - genericKey:
              descriptorValue: slowpath
    routeAction:
      single:
        upstream:
          name: backend
          namespace: gloo-system
