metadata:
  name: default
  namespace: gloo-system
  resourceVersion: "4"
status:
  reportedBy: gateway
  state: Accepted
  subresourceStatuses:
    '*v1.Proxy.gloo-system.gateway-proxy':
      reportedBy: gloo
      state: Accepted
virtualHost:
  domains:
  - '*'
  options:
    extauth:
      customAuth: {}
  routes:
  - matchers:
    - prefix: /
    options:
      ratelimit:
        rateLimits:
          - actions:
              - genericKey:
                  descriptorValue: "slowpath"
    routeAction:
      single:
        upstream:
          name: backend
          namespace: gloo-system
