metadata:
  name: extauth
  namespace: gloo-system
  resourceVersion: "4"
namespacedStatuses:
  statuses:
    gloo-system:
      reportedBy: gloo
      state: Accepted
static:
  hosts:
  - addr: extauth
    port: 4000
useHttp2: true
