metadata:
  name: ratelimit
  namespace: gloo-system
  resourceVersion: "6"
namespacedStatuses:
  statuses:
    gloo-system:
      reportedBy: gloo
      state: Accepted
static:
  hosts:
  - addr: ratelimit
    port: 8081
useHttp2: true
