---
domain: backend
descriptors:
  - key: generic_key
    value: slowpath
    rate_limit:
      requests_per_unit: 2
      unit: minute
  - key: ratelimitkey
    descriptors:
      - key: path
        rate_limit:
          requests_per_unit: 100
          unit: minute
